apiVersion: v1
kind: Service
metadata:
  name: minio-service
  labels:
    app: minio-service
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.ports.minio }}
    targetPort: {{ .Values.ports.minio }}
    name: minio
  - port: {{ .Values.ports.minioconsole }}
    targetPort: {{ .Values.ports.minioconsole }}
    name: minio-console
  selector:
    app: minio