apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio-deploy
  labels:
    name: minio-deplay
    app: {{ .Values.app.name }}
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
      name: minio
    spec:
      containers:
      - name: minio
        image: quay.io/minio/minio:latest
        command:
        - /bin/bash
        - -c
        args: 
        - minio server /data --console-address :{{ .Values.ports.minioconsole }}
        ports:
        - containerPort: {{ .Values.ports.minio }}
          name: minio
        - containerPort: {{ .Values.ports.minioconsole }}
          name: minio-console
        env:
        - name: MINIO_ROOT_USER
          value: testkey
        - name: MINIO_ROOT_PASSWORD
          value: secretkey
        volumeMounts:
        - mountPath: /data
          name: localvolume # Corresponds to the `spec.volumes` Persistent Volume
      volumes:
      - name: localvolume
        hostPath: # MinIO generally recommends using locally-attached volumes
          path: /run/desktop/mnt/host/wsl/miniovolume # Specify a path to a local drive or volume on the Kubernetes worker node. Note this is not working in WSL.
          type: DirectoryOrCreate # The path to the last directory must exist
