apiVersion: v1
kind: Service
metadata:
  name: musicapp-service
  labels:
    name: musicapp-service
    app: musicapp
spec:
  type: LoadBalancer
  ports:
    - port: 5002
      targetPort: 5002
      #nodePort: 30002
  selector:
    app: musicapp