apiVersion: v1
kind: Service
metadata:
  name: musicapp-service
  labels:
    name: musicapp-service
    app: musicapp
spec:
  type: LoadBalancer
  ports:
    - port: {{ .Values.ports.flask }}
      targetPort: {{ .Values.ports.flask }}
  selector:
    app: musicapp