apiVersion: v1
kind: Service
metadata:
  name: mysql-controller
  labels:
    name: mysql-controller
    app: musicapp
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.ports.mysql }}
      targetPort: {{ .Values.ports.mysql }} 
  selector:
    name: mysql-pod
    app: musicapp