apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  labels:
    name: mysql-service
    app: {{ .Values.app.name }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.ports.mysql }}
      targetPort: {{ .Values.ports.mysql }} 
  selector:
    name: mysql-pod
    app: {{ .Values.app.name }}