# Deploys a new MinIO Pod into the default Kubernetes namespace
#
# The `spec.containers[0].args` contains the command run on the pod
# The `/data` directory corresponds to the `spec.containers[0].volumeMounts[0].mountPath`
# That mount path corresponds to a Kubernetes HostPath which binds `/data` to a local drive or volume on the worker node where the pod runs
# 
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: minio
  name: minio
spec:
  containers:
  - name: minio
    image: quay.io/minio/minio:latest
    command:
    - /bin/bash
    - -c
    args: 
    - minio server /data --console-address :9001
    ports:
    - containerPort: 9000
      name: minio
    - containerPort: 9001
      name: minio-console
    env:
    - name: MINIO_ROOT_USER
      value: testkey
    - name: MINIO_ROOT_PASSWORD
      value: secretkey
    volumeMounts:
    - mountPath: /data
      name: localvolume # Corresponds to the `spec.volumes` Persistent Volume
    readinessProbe:
      httpGet:
        path: /minio/health/ready
        port: 9000
      initialDelaySeconds: 60
      periodSeconds: 20
  volumes:
  - name: localvolume
    persistentVolumeClaim:
      claimName: minio-pvc