apiVersion: v1
kind: Service
metadata:
  name: minio-service
  labels:
    app: minio-service
spec:
  type: ClusterIP
  ports:
  - port: 9000
    targetPort: 9000
    #nodePort: 30010
    name: minio
  - port: 9001
    targetPort: 9001
    #nodePort: 30011
    name: minio-console
  selector:
    app: minio