apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio-deploy
  labels:
    name: minio-deplay
    app: musicapp
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
      name: minio
    spec:
      containers:
      - name: minio
        image: quay.io/minio/minio:latest
        command:
        - /bin/bash
        - -c
        args: 
        - minio server /data --console-address :9001
        ports:
        - containerPort: 9000
          name: minio
        - containerPort: 9001
          name: minio-console
        env:
        - name: MINIO_ROOT_USER
          value: testkey
        - name: MINIO_ROOT_PASSWORD
          value: secretkey
      volumes:
      - name: localvolume
        hostPath: # MinIO generally recommends using locally-attached volumes
          path: /home/eoincarley/spotify/kubernetes/static # Specify a path to a local drive or volume on the Kubernetes worker node
          type: DirectoryOrCreate # The path to the last directory must exist