apiVersion: v1
kind: Pod
metadata:
  labels:
    app: musicapp
  name: musicapp
spec:
  containers:
  - name: musicapp
    image: eoincarley/musicapp:latest
    ports:
    - containerPort: 5002
      name: musicapp