apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  labels: 
    name: mysql-pod
    app: musicapp
spec:
  containers:
    - name: spotifydb
      image: mysql
      ports:
        - containerPort: 3306
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: "mypassword"
        - name: MYSQL_DATABASE
          value: "spotifydb"