apiVersion: v1
kind: Service
metadata:
  name: mysql-controller
  labels:
    name: mysql-controller
    app: musicapp
spec:
  type: ClusterIP
  ports:
    - port: 3306
      targetPort: 3306 
    #  nodePort: 30006
  selector:
    name: mysql-pod
    app: musicapp